export const APPLICANTS = [
  {
    id: "TRV-2026-004821",
    name: "Priya Sharma",
    dob: "May 13, 1992",
    nationality: "India",
    country: "India",
    applicationType: "TRV",
    biometrics: "Received",
    feePayment: "Paid",
    submitted: "Feb 28, 2026",
    status: "incomplete",
    forms: [
      { id: "IMM5257", name: "IMM 5257", desc: "Application for Temporary Resident Visa", status: "signed" },
      { id: "IMM5707", name: "IMM 5707", desc: "Family Information", status: "validated" },
      { id: "IMM5476", name: "IMM 5476", desc: "Use of a Representative", status: "submitted" },
      { id: "IMM5475", name: "IMM 5475", desc: "Authority to Release Personal Information", status: "signed" },
      { id: "IMM5409", name: "IMM 5409", desc: "Statutory Declaration of Common-law Union", status: "missing" },
    ],
    documents: [
      { id: "passport", name: "Passport Information Page", type: "PDF", status: "present" },
      { id: "photos", name: "Passport-Sized Photos", type: "Image", status: "present" },
      { id: "financial", name: "Proof of Financial Support", type: "PDF", status: "present" },
      { id: "purpose", name: "Purpose of Travel Letter", type: "PDF", status: "missing" },
      { id: "marriage", name: "Marriage Certificate", type: "PDF", status: "missing" },
    ],
    notes: [
      { actor: "System", time: "Feb 28, 2026 09:14", text: "Application received and assigned to queue." },
      { actor: "J. Thompson", time: "Mar 1, 2026 11:02", text: "Initial document review started. Missing IMM 5409 and two supporting documents." },
    ],
  },
  {
    id: "TRV-2026-004756",
    name: "Carlos Mendoza Rivera",
    dob: "Aug 7, 1985",
    nationality: "Mexico",
    country: "Mexico",
    applicationType: "TRV",
    biometrics: "Received",
    feePayment: "Paid",
    submitted: "Feb 24, 2026",
    status: "incomplete",
    forms: [
      { id: "IMM5257", name: "IMM 5257", desc: "Application for Temporary Resident Visa", status: "signed" },
      { id: "IMM5707", name: "IMM 5707", desc: "Family Information", status: "signed" },
      { id: "IMM5476", name: "IMM 5476", desc: "Use of a Representative", status: "missing" },
      { id: "IMM5475", name: "IMM 5475", desc: "Authority to Release Personal Information", status: "missing" },
      { id: "IMM5409", name: "IMM 5409", desc: "Statutory Declaration of Common-law Union", status: "submitted" },
    ],
    documents: [
      { id: "passport", name: "Passport Information Page", type: "PDF", status: "present" },
      { id: "photos", name: "Passport-Sized Photos", type: "Image", status: "present" },
      { id: "financial", name: "Proof of Financial Support", type: "PDF", status: "missing" },
      { id: "purpose", name: "Purpose of Travel Letter", type: "PDF", status: "present" },
      { id: "immigration", name: "Proof of Immigration Status", type: "PDF", status: "missing" },
    ],
    notes: [
      { actor: "System", time: "Feb 24, 2026 14:30", text: "Application received and assigned to queue." },
    ],
  },
  {
    id: "TRV-2026-004902",
    name: "Amina Hassan Osman",
    dob: "Mar 19, 1998",
    nationality: "Somalia",
    country: "Somalia",
    applicationType: "TRV",
    biometrics: "Pending",
    feePayment: "Paid",
    submitted: "Mar 4, 2026",
    status: "pending",
    forms: [
      { id: "IMM5257", name: "IMM 5257", desc: "Application for Temporary Resident Visa", status: "submitted" },
      { id: "IMM5707", name: "IMM 5707", desc: "Family Information", status: "submitted" },
      { id: "IMM5476", name: "IMM 5476", desc: "Use of a Representative", status: "missing" },
      { id: "IMM5475", name: "IMM 5475", desc: "Authority to Release Personal Information", status: "missing" },
      { id: "IMM5409", name: "IMM 5409", desc: "Statutory Declaration of Common-law Union", status: "missing" },
    ],
    documents: [
      { id: "passport", name: "Passport Information Page", type: "PDF", status: "present" },
      { id: "photos", name: "Passport-Sized Photos", type: "Image", status: "missing" },
      { id: "financial", name: "Proof of Financial Support", type: "PDF", status: "missing" },
      { id: "purpose", name: "Purpose of Travel Letter", type: "PDF", status: "missing" },
    ],
    notes: [
      { actor: "System", time: "Mar 4, 2026 08:22", text: "Application received. Awaiting biometrics." },
    ],
  },
  {
    id: "TRV-2026-004658",
    name: "Wei Chen",
    dob: "Nov 2, 1990",
    nationality: "China",
    country: "China",
    applicationType: "TRV",
    biometrics: "Received",
    feePayment: "Paid",
    submitted: "Feb 17, 2026",
    status: "complete",
    forms: [
      { id: "IMM5257", name: "IMM 5257", desc: "Application for Temporary Resident Visa", status: "signed" },
      { id: "IMM5707", name: "IMM 5707", desc: "Family Information", status: "validated" },
      { id: "IMM5476", name: "IMM 5476", desc: "Use of a Representative", status: "signed" },
      { id: "IMM5475", name: "IMM 5475", desc: "Authority to Release Personal Information", status: "signed" },
      { id: "IMM5409", name: "IMM 5409", desc: "Statutory Declaration of Common-law Union", status: "validated" },
    ],
    documents: [
      { id: "passport", name: "Passport Information Page", type: "PDF", status: "present" },
      { id: "photos", name: "Passport-Sized Photos", type: "Image", status: "present" },
      { id: "financial", name: "Proof of Financial Support", type: "PDF", status: "present" },
      { id: "purpose", name: "Purpose of Travel Letter", type: "PDF", status: "present" },
      { id: "marriage", name: "Marriage Certificate", type: "PDF", status: "present" },
    ],
    notes: [
      { actor: "System", time: "Feb 17, 2026 10:05", text: "Application received and assigned." },
      { actor: "J. Thompson", time: "Feb 20, 2026 15:44", text: "All documents verified. Application complete." },
    ],
  },
  {
    id: "TRV-2026-004788",
    name: "Oluwafemi Adeyemi",
    dob: "Jun 14, 1987",
    nationality: "Nigeria",
    country: "Nigeria",
    applicationType: "TRV",
    biometrics: "Received",
    feePayment: "Pending",
    submitted: "Mar 7, 2026",
    status: "pending",
    forms: [
      { id: "IMM5257", name: "IMM 5257", desc: "Application for Temporary Resident Visa", status: "submitted" },
      { id: "IMM5707", name: "IMM 5707", desc: "Family Information", status: "submitted" },
      { id: "IMM5476", name: "IMM 5476", desc: "Use of a Representative", status: "submitted" },
      { id: "IMM5475", name: "IMM 5475", desc: "Authority to Release Personal Information", status: "unsigned" },
      { id: "IMM5409", name: "IMM 5409", desc: "Statutory Declaration of Common-law Union", status: "submitted" },
    ],
    documents: [
      { id: "passport", name: "Passport Information Page", type: "PDF", status: "present" },
      { id: "photos", name: "Passport-Sized Photos", type: "Image", status: "present" },
      { id: "financial", name: "Proof of Financial Support", type: "PDF", status: "present" },
      { id: "purpose", name: "Purpose of Travel Letter", type: "PDF", status: "present" },
    ],
    notes: [
      { actor: "System", time: "Mar 7, 2026 12:00", text: "Application received. Fee payment pending." },
    ],
  },
];
